### ISSUE TITLE
Export to Excel using PS module ImportExcel?

### ISSUE THREAD

**Issue by martin-guth** [VladDBA/PSBlitz#170]
Hi @VladDBA,

this project sounds promising...I will give it a shot.
You write that export to Excel is possible only when Excel is installed on the system.
Have you considered to use the module ImportExcel.
I have a blog post on it how to get started: http://www.martinguth.de/reporting/exporting-to-excel-from-powershell-without-having-excel-installed/

Cheers

Martin

**Comment by VladDBA** [comment]
Hi @martin-guth,

Thank you for the feedback!
I did consider the ImportExcel module as an option at the beginning. The issue is that some Orgs might have stricter security policies than others, strict enough to not allow for additional modules to be installed via PS.
But most Orgs do use the Microsoft Office suite, and, for the rare cases where that's not viable, there's the option to export to HTML just like Oracle's AWR reports.

I'll look into it a bit more, maybe I can use it as self-contained resource and not require it to be installed separately
