### ISSUE TITLE
Script execution was interrupted - v2.2.0

### ISSUE THREAD

**Issue by bonfi** [VladDBA/PSBlitz#39]
With latest version (v2.2.0), when i execute:
`.\PSBlitz.ps1 XXXPRODSQL01\XX1 -IsIndepth Y -CheckDB CORESQL7`
i obtain this error:
"Retrieving instance information.
Script execution was interrupted.
Finishing up..."

With the older version v2.1.1 the same command mentioned above works without any problems.

**Comment by VladDBA** [comment]
Hello,
I can't seem to reproduce your exact scenario yet, but there is an issue with sp_BlitzLock for which I'll have to open an issue in Brent's repository.
Since in your case it seems to be failing when running GetInstanceInfo.sql, can you please run [GetInstanceInfo.sql](https://github.com/VladDBA/PSBlitz/blob/main/Resources/GetInstanceInfo.sql) against that instance and let me know if any of the result sets errors out?

**Comment by bonfi** [comment]
i've executed [GetInstanceInfo.sql](https://github.com/VladDBA/PSBlitz/blob/main/Resources/GetInstanceInfo.sql) on my sql Server 2012 SP4 istance and i obtain this error:

Msg 207, Level 16, State 1, Line 50
Invalid column name 'socket_count'.
Msg 207, Level 16, State 1, Line 50
Invalid column name 'cores_per_socket'.

**Comment by VladDBA** [comment]
Thank you for testing!
I'll have a fixed version out by tomorrow.

**Comment by VladDBA** [comment]
Hi @bonfi,
Should be all set.
This also helped me catch an issue on SQL Server 2012 with the Stats and Index info script.
