### ISSUE TITLE
"-ToHTML N" to force output in Excel format

### ISSUE THREAD

**Issue by bonfi** [VladDBA/PSBlitz#88]
Hello, is it possible to have the same output in excel even if office is not installed in the server? 
or to have both: HTML and Excel

"-ToHTML N" is just an idea, or you could create the parameter "-ToExcel Y"

Thanks

**Comment by VladDBA** [comment]
Hi @bonfi,

Unfortunately, at the moment, there is no way to have viable output to excel file without Excel being installed on the machine where PSBlitz is being executed.

As part of the execution flow, PSBlitz opens Exce, it then loads the excel output template into it, and uses Excel to populate the file and save it. 

So, even if I would suppress the switch to HTML when Excel isn't present, it wouldn't work, it would just cause PSBlitz to error out when trying to run Excel.

The only alternative I could think of would be to adapt PSBlitz to use the [ImportExcel](https://www.powershellgallery.com/packages/ImportExcel/7.8.4) PowerShell module on machines where Excel isn't present, but this implies on users having to install an additional PowerShell module in order to be able to output to excel.

Thank you.

**Comment by bonfi** [comment]
ok clear, thank you. I will try to run it from a pc with excel installed
